import { NextResponse } from "next/server";
import { catalogDb } from "@/lib/db";
import { sanitizeImageList } from "@/lib/image-url";

// The feed is generated on demand and cached by its response headers instead
// of being periodically regenerated by ISR.
export const dynamic = "force-dynamic";

const BASE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.gocmenperde.com.tr"
).replace(/\/$/, "");

// Google Merchant Center RSS 2.0 feed.
// Merchant Center'ın tanıdığı GTIN alanı g:gtin (tek alan, uzunluktan bağımsız).
// gtin8/gtin12/gtin13/gtin14 sadece Content API'de kullanılır — XML feed'de geçersiz.
// original_price alanı da tanınmıyor; indirim için g:price (orijinal) + g:sale_price kullanılmalı.
// Ürünün gerçek kategori slug'ına göre Merchant Center sınıfı seçilir.
// Koltuk örtüsü ve çarşaf gibi ürünler Window Treatments altında gönderilmez.
const GOOGLE_CATEGORY_BY_SLUG: Record<string, string> = {
  "tul-perde": "Home & Garden > Decor > Window Treatments > Curtains & Drapes",
  "fonperdeler": "Home & Garden > Decor > Window Treatments > Curtains & Drapes",
  "ormetulperde": "Home & Garden > Decor > Window Treatments > Curtains & Drapes",
  "stor-perde": "Home & Garden > Decor > Window Treatments > Shades",
  "zebra-perde": "Home & Garden > Decor > Window Treatments > Shades",
  "plise-perde": "Home & Garden > Decor > Window Treatments > Shades",
  "guneslik": "Home & Garden > Decor > Window Treatments > Shades",
  "koltuk": "Home & Garden > Decor > Furniture Covers",
  "carsaf": "Home & Garden > Linens & Bedding > Bedding",
};

const FEED_CATEGORY_SLUGS = Object.keys(GOOGLE_CATEGORY_BY_SLUG);
const FALLBACK_FREE_SHIPPING_THRESHOLD = 1500;
const FALLBACK_SHIPPING_FEE = 79.9;

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function isValidGtin(value: string | null): value is string {
  if (!value) return false;
  const digits = value.replace(/\s/g, "");
  if (!/^\d{8,14}$/.test(digits)) return false;

  let checksum = 0;
  for (let index = digits.length - 2, position = 0; index >= 0; index -= 1, position += 1) {
    checksum += Number(digits[index]) * (position % 2 === 0 ? 3 : 1);
  }
  return (10 - (checksum % 10)) % 10 === Number(digits.at(-1));
}

function toFiniteNumber(value: unknown, fallback: number) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function getSpecSummary(value: unknown): string[] {
  if (!value || typeof value !== "object" || Array.isArray(value)) return [];
  return Object.entries(value as Record<string, unknown>)
    .filter(([, item]) => typeof item === "string" || typeof item === "number")
    .slice(0, 5)
    .map(([key, item]) => `${key}: ${item}`);
}

function buildMerchantDescription(product: {
  name: string;
  description: string | null;
  category: { name: string } | null;
  brand: { name: string } | null;
  tags: string[];
  features: string | null;
  specs: unknown;
}) {
  const parts = [
    product.description?.trim(),
    `${product.name}${product.brand?.name ? ` — ${product.brand.name}` : ""}${product.category?.name ? ` — ${product.category.name}` : ""}.`,
    product.features ? `Öne çıkan özellikler: ${product.features}.` : null,
    ...getSpecSummary(product.specs),
    product.tags.length > 0 ? `İlgili ürün bilgileri: ${product.tags.slice(0, 6).join(", ")}.` : null,
    "Göçmen Perde'de ürün, ölçü, stok ve teslimat bilgilerini inceleyerek satın alabilirsiniz.",
  ];
  return parts.filter(Boolean).join(" ").slice(0, 5000);
}

export async function GET() {
  try {
    const products = await catalogDb.product.findMany({
      where: {
        isActive: true,
        category: { slug: { in: FEED_CATEGORY_SLUGS } },
      },
      select: {
        id: true,
        name: true,
        slug: true,
        description: true,
        price: true,
        comparePrice: true,
        stock: true,
        images: true,
        barcode: true,
        serialNumber: true,
        tags: true,
        features: true,
        specs: true,
        isMeter: true,
        isSquareMeter: true,
        category: { select: { name: true, slug: true } },
        brand:    { select: { name: true } },
      },
      orderBy: { updatedAt: "desc" },
    });

    let shippingSettings = {
      freeShippingThreshold: FALLBACK_FREE_SHIPPING_THRESHOLD,
      shippingFee: FALLBACK_SHIPPING_FEE,
    };
    try {
      const settings = await catalogDb.siteSettings.findUnique({
        where: { id: "global" },
        select: { freeShippingThreshold: true, shippingFee: true },
      });
      if (settings) {
        shippingSettings = {
          freeShippingThreshold: toFiniteNumber(
            settings.freeShippingThreshold,
            FALLBACK_FREE_SHIPPING_THRESHOLD,
          ),
          shippingFee: toFiniteNumber(settings.shippingFee, FALLBACK_SHIPPING_FEE),
        };
      }
    } catch {
      // Feed generation can still use the same defaults as checkout.
    }

    const now = new Date().toUTCString();

    const items = products.map((p) => {
      const currentPrice  = Number(p.price);
      const comparePrice  = p.comparePrice ? Number(p.comparePrice) : null;
      const inStock       = (p.stock ?? 0) > 0;
      const images        = sanitizeImageList(p.images, 10);
      const mainImage     = images[0] ?? "";
      const extraImages   = images.slice(1, 10);
      const barcode       = p.barcode?.replace(/\s/g, "") ?? null;
      const serialNumber  = p.serialNumber?.trim() || null;
      const categorySlug  = p.category?.slug ?? "";
      const googleCategory = GOOGLE_CATEGORY_BY_SLUG[categorySlug];
      const description   = buildMerchantDescription(p);
      const productTypePrefix = categorySlug === "koltuk" || categorySlug === "carsaf"
        ? "Ev Tekstili"
        : "Perde";
      const productType = p.category?.name
        ? `${productTypePrefix} > ${p.category.name}`
        : null;
      const title         = p.category?.name
        && !p.name.toLocaleLowerCase("tr-TR").includes(p.category.name.toLocaleLowerCase("tr-TR"))
        ? `${p.name} | ${p.category.name}`
        : p.name;

      // Doğru fiyat mantığı:
      // İndirim yoksa: g:price = satış fiyatı, g:sale_price yok
      // İndirim varsa: g:price = orijinal fiyat (comparePrice), g:sale_price = indirimlii fiyat
      const hasDiscount   = comparePrice !== null && comparePrice > currentPrice;
      const listedPrice   = hasDiscount ? comparePrice!.toFixed(2) : currentPrice.toFixed(2);
      const salePrice     = hasDiscount ? currentPrice.toFixed(2) : null;
      const shippingPrice = currentPrice >= shippingSettings.freeShippingThreshold
        ? 0
        : shippingSettings.shippingFee;

      // Geçersiz barkodu GTIN olarak göndermeyin. SKU merchant içi kod olduğu
      // için otomatik olarak üretici MPN'i sayılmaz.
      const hasValidGtin = isValidGtin(barcode);
      const hasIdentifier = hasValidGtin || !!serialNumber;
      const unitPricing = p.isMeter
        ? `<g:unit_pricing_measure>1 m</g:unit_pricing_measure>
       <g:unit_pricing_base_measure>1 m</g:unit_pricing_base_measure>`
        : p.isSquareMeter
          ? `<g:unit_pricing_measure>1 m2</g:unit_pricing_measure>
       <g:unit_pricing_base_measure>1 m2</g:unit_pricing_base_measure>`
          : "";

      return `
    <item>
      <g:id>${escapeXml(p.id)}</g:id>
      <g:title>${escapeXml(title.slice(0, 150))}</g:title>
      <g:description>${escapeXml(description)}</g:description>
      <g:link>${BASE_URL}/products/${escapeXml(p.slug)}</g:link>
      ${mainImage ? `<g:image_link>${escapeXml(mainImage)}</g:image_link>` : ""}
      ${extraImages.map((img) => `<g:additional_image_link>${escapeXml(img)}</g:additional_image_link>`).join("\n      ")}
      <g:availability>${inStock ? "in_stock" : "out_of_stock"}</g:availability>
      <g:price>${listedPrice} TRY</g:price>
      ${salePrice ? `<g:sale_price>${salePrice} TRY</g:sale_price>` : ""}
      <g:brand>${escapeXml(p.brand?.name ?? "Göçmen Perde")}</g:brand>
      <g:condition>new</g:condition>
      <g:google_product_category>${escapeXml(googleCategory)}</g:google_product_category>
      ${productType ? `<g:product_type>${escapeXml(productType)}</g:product_type>` : ""}
      ${serialNumber ? `<g:mpn>${escapeXml(serialNumber)}</g:mpn>` : ""}
      ${hasValidGtin ? `<g:gtin>${escapeXml(barcode!)}</g:gtin>` : ""}
      <g:identifier_exists>${hasIdentifier ? "yes" : "no"}</g:identifier_exists>
      ${unitPricing}
      <g:custom_label_0>${escapeXml(categorySlug || "perde")}</g:custom_label_0>
      <g:custom_label_1>${hasDiscount ? "indirimli" : "standart"}</g:custom_label_1>
      <g:custom_label_2>${inStock ? "stokta" : "stok-yok"}</g:custom_label_2>
      <g:shipping>
        <g:country>TR</g:country>
        <g:service>Standart Kargo</g:service>
        <g:price>${shippingPrice.toFixed(2)} TRY</g:price>
      </g:shipping>
    </item>`;
    });

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">
  <channel>
    <title>Göçmen Perde — Google Shopping Feed</title>
    <link>${BASE_URL}</link>
    <description>Göçmen Perde tüm ürün kataloğu</description>
    <lastBuildDate>${now}</lastBuildDate>
${items.join("\n")}
  </channel>
</rss>`;

    return new NextResponse(xml, {
      status: 200,
      headers: {
        "Content-Type": "application/xml; charset=utf-8",
        // Merchant Center price, stock and shipping data must not remain
        // behind a long CDN cache when the source is manually refreshed.
        "Cache-Control": "no-store, max-age=0, must-revalidate",
        "CDN-Cache-Control": "no-store",
        "Vercel-CDN-Cache-Control": "no-store",
      },
    });
  } catch (err) {
    console.error("[Feed/Google]", err);
    return new NextResponse("Feed oluşturulamadı", { status: 500 });
  }
}
