import { NextResponse } from "next/server";
import { catalogDb } from "@/lib/db";
import { sanitizeImageList } from "@/lib/image-url";

// The feed is generated on demand and cached by its response headers instead
// of being periodically regenerated by ISR.
export const dynamic = "force-dynamic";

const BASE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.gocmenperde.com.tr"
).replace(/\/$/, "");

// Google Merchant Center RSS 2.0 feed.
// Merchant Center'ın tanıdığı GTIN alanı g:gtin (tek alan, uzunluktan bağımsız).
// gtin8/gtin12/gtin13/gtin14 sadece Content API'de kullanılır — XML feed'de geçersiz.
// original_price alanı da tanınmıyor; indirim için g:price (orijinal) + g:sale_price kullanılmalı.
const GOOGLE_CATEGORY = "Arts & Entertainment > Hobbies & Creative Arts > Stationery";

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export async function GET() {
  try {
    const products = await catalogDb.product.findMany({
      where: { isActive: true },
      select: {
        id: true,
        name: true,
        slug: true,
        description: true,
        price: true,
        comparePrice: true,
        stock: true,
        images: true,
        barcode: true,
        sku: true,
        category: { select: { name: true } },
        brand:    { select: { name: true } },
      },
      orderBy: { updatedAt: "desc" },
    });

    const now = new Date().toUTCString();

    const items = products.map((p) => {
      const currentPrice  = Number(p.price);
      const comparePrice  = p.comparePrice ? Number(p.comparePrice) : null;
      const inStock       = (p.stock ?? 0) > 0;
      const images        = sanitizeImageList(p.images, 10);
      const mainImage     = images[0] ?? "";
      const extraImages   = images.slice(1, 10);
      const barcode       = p.barcode ?? null;
      const sku           = p.sku ?? null;
      const description   = p.description
        ?? `${p.name}${p.brand?.name ? ` — ${p.brand.name}` : ""}${p.category?.name ? ` — ${p.category.name}` : ""}. Göçmen Perde'de uygun fiyatla satın alın.`;

      // Doğru fiyat mantığı:
      // İndirim yoksa: g:price = satış fiyatı, g:sale_price yok
      // İndirim varsa: g:price = orijinal fiyat (comparePrice), g:sale_price = indirimlii fiyat
      const hasDiscount   = comparePrice !== null && comparePrice > currentPrice;
      const listedPrice   = hasDiscount ? comparePrice!.toFixed(2) : currentPrice.toFixed(2);
      const salePrice     = hasDiscount ? currentPrice.toFixed(2) : null;

      // GTIN: RSS feed'de g:gtin tek alan — gtin8/12/13/14 Content API'ye özgüdür
      const isValidGtin   = barcode ? /^\d{8,14}$/.test(barcode) : false;
      const hasIdentifier = isValidGtin || !!sku;

      return `
    <item>
      <g:id>${escapeXml(p.id)}</g:id>
      <g:title>${escapeXml(p.name)}</g:title>
      <g:description>${escapeXml(description.slice(0, 5000))}</g:description>
      <g:link>${BASE_URL}/products/${escapeXml(p.slug)}</g:link>
      ${mainImage ? `<g:image_link>${escapeXml(mainImage)}</g:image_link>` : ""}
      ${extraImages.map((img) => `<g:additional_image_link>${escapeXml(img)}</g:additional_image_link>`).join("\n      ")}
      <g:availability>${inStock ? "in_stock" : "out_of_stock"}</g:availability>
      <g:price>${listedPrice} TRY</g:price>
      ${salePrice ? `<g:sale_price>${salePrice} TRY</g:sale_price>` : ""}
      <g:brand>${escapeXml(p.brand?.name ?? "Göçmen Perde")}</g:brand>
      <g:condition>new</g:condition>
      <g:google_product_category>${escapeXml(GOOGLE_CATEGORY)}</g:google_product_category>
      ${p.category?.name ? `<g:product_type>${escapeXml(p.category.name)}</g:product_type>` : ""}
      ${sku ? `<g:mpn>${escapeXml(sku)}</g:mpn>` : ""}
      ${isValidGtin ? `<g:gtin>${escapeXml(barcode!)}</g:gtin>` : ""}
      <g:identifier_exists>${hasIdentifier ? "yes" : "no"}</g:identifier_exists>
      <g:shipping>
        <g:country>TR</g:country>
        <g:service>Standart Kargo</g:service>
        <g:price>0 TRY</g:price>
      </g:shipping>
    </item>`;
    });

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">
  <channel>
    <title>Göçmen Perde — Google Shopping Feed</title>
    <link>${BASE_URL}</link>
    <description>Göçmen Perde tüm ürün kataloğu</description>
    <lastBuildDate>${now}</lastBuildDate>
${items.join("\n")}
  </channel>
</rss>`;

    return new NextResponse(xml, {
      status: 200,
      headers: {
        "Content-Type": "application/xml; charset=utf-8",
        "Cache-Control": "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400",
        "CDN-Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
        "Vercel-CDN-Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
      },
    });
  } catch (err) {
    console.error("[Feed/Google]", err);
    return new NextResponse("Feed oluşturulamadı", { status: 500 });
  }
}
