import { db } from "@/lib/db";
import ProductCard from "@/components/store/product-card";
import ProductFilters from "@/components/store/product-filters";
export const revalidate = 60;
interface SearchParams { category?: string; brand?: string; minPrice?: string; maxPrice?: string; sort?: string; q?: string; page?: string; }
export default async function ProductsPage({ searchParams }: { searchParams: SearchParams }) {
  const page = Number(searchParams.page ?? 1); const take = 24;
  const where = { isActive: true, ...(searchParams.category && { category: { slug: searchParams.category } }), ...(searchParams.brand && { brand: { slug: searchParams.brand } }), ...(searchParams.q && { name: { contains: searchParams.q, mode: "insensitive" as const } }), ...((searchParams.minPrice || searchParams.maxPrice) && { price: { ...(searchParams.minPrice && { gte: Number(searchParams.minPrice) }), ...(searchParams.maxPrice && { lte: Number(searchParams.maxPrice) }) } }) };
  const orderBy: any = searchParams.sort === "price-asc" ? { price: "asc" } : searchParams.sort === "price-desc" ? { price: "desc" } : searchParams.sort === "oldest" ? { createdAt: "asc" } : { createdAt: "desc" };
  const [products, total, categories, brands] = await Promise.all([db.product.findMany({ where, include: { brand: true, category: true }, orderBy, take, skip: (page - 1) * take }), db.product.count({ where }), db.category.findMany({ where: { parentId: null }, orderBy: { name: "asc" } }), db.brand.findMany({ orderBy: { name: "asc" } })]);
  return <div className="max-w-7xl mx-auto px-4 py-8"><div className="mb-8"><h1 className="text-3xl font-bold text-zinc-900 dark:text-white">Tüm Ürünler</h1><p className="text-zinc-500 mt-1">{total} ürün bulundu</p></div><div className="flex flex-col md:flex-row gap-8"><aside className="w-full md:w-64 flex-shrink-0"><ProductFilters categories={categories} brands={brands} /></aside><div className="flex-1">{products.length===0?<div className="text-center py-16 text-zinc-400">Ürün bulunamadı.</div>:<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">{products.map((p)=><ProductCard key={p.id} product={p} />)}</div>}<div className="mt-8 flex justify-center gap-2">{Array.from({ length: Math.ceil(total / take) }, (_, i) => i + 1).map((p) => <a key={p} href={`?page=${p}`} className={`w-10 h-10 rounded-xl flex items-center justify-center text-sm font-medium transition-colors ${p === page ? "bg-zinc-900 dark:bg-white text-white dark:text-zinc-900" : "bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700"}`}>{p}</a>)}</div></div></div></div>;
}
