// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/store-design/BoldAmber.tsx": () => import("../components/mockups/store-design/BoldAmber.tsx"),
  "./components/mockups/store-design/ModernLight.tsx": () => import("../components/mockups/store-design/ModernLight.tsx"),
  "./components/mockups/store-design/PremiumDark.tsx": () => import("../components/mockups/store-design/PremiumDark.tsx"),
  "./components/mockups/banner-redesign/Current.tsx": () => import("../components/mockups/banner-redesign/Current.tsx"),
  "./components/mockups/banner-redesign/PremiumEditorial.tsx": () => import("../components/mockups/banner-redesign/PremiumEditorial.tsx")
};
