export const fallbackProducts = [
  {
    id: "mock-1",
    slug: "faber-castell-12li-kuru-boya-seti",
    name: "Faber-Castell 12'li Kuru Boya Seti",
    price: 89.9,
    comparePrice: 119.9,
    isFeatured: true,
    stock: 150,
    images: ["https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600"],
    brand: { name: "Faber-Castell", slug: "faber-castell" },
    category: { name: "Boyalar & Renkler", slug: "boyalar-renkler" },
    reviews: [
      { id: "r1", rating: 5, comment: "Renkleri çok canlı, kalitesi harika.", user: { name: "Ayşe K." }, createdAt: new Date().toISOString() },
      { id: "r2", rating: 4, comment: "Fiyat performans mükemmel.", user: { name: "Murat Ç." }, createdAt: new Date().toISOString() },
    ],
    description: "Faber-Castell 12'li Kuru Boya Seti günlük kullanım ve profesyonel ihtiyaçlar için özenle seçildi. Dayanıklı yapısı ve kaliteli malzemesiyle uzun süreli performans sunar.",
  },
  {
    id: "mock-2",
    slug: "staedtler-triplus-fineliner-10lu",
    name: "Staedtler Triplus Fineliner 10'lu Set",
    price: 145,
    comparePrice: 189,
    isFeatured: true,
    stock: 80,
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600"],
    brand: { name: "Staedtler", slug: "staedtler" },
    category: { name: "Kalemler & Yazı Gereçleri", slug: "kalemler-yazi-gerecleri" },
    reviews: [
      { id: "r3", rating: 5, comment: "Teknik çizim için mükemmel.", user: { name: "Can D." }, createdAt: new Date().toISOString() },
    ],
    description: "Staedtler Triplus Fineliner 10'lu Set ile profesyonel çizimler yapın.",
  },
  {
    id: "mock-3",
    slug: "pelikan-gunluk-ajanda-2025",
    name: "Pelikan Günlük Ajanda 2025",
    price: 129.9,
    comparePrice: null,
    isFeatured: true,
    stock: 200,
    images: ["https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600"],
    brand: { name: "Pelikan", slug: "pelikan" },
    category: { name: "Defterler & Ajandalar", slug: "defterler-ajandalar" },
    reviews: [
      { id: "r4", rating: 5, comment: "Kargo çok hızlı geldi.", user: { name: "Zeynep Ö." }, createdAt: new Date().toISOString() },
      { id: "r5", rating: 4, comment: "Kaliteli bir ajanda, her gün kullanıyorum.", user: { name: "Elif N." }, createdAt: new Date().toISOString() },
    ],
    description: "Pelikan Günlük Ajanda 2025 ile tüm planlarınızı organize edin.",
  },
  {
    id: "mock-4",
    slug: "pentel-energel-jel-kalem-5li",
    name: "Pentel EnerGel Jel Kalem 5'li",
    price: 67.5,
    comparePrice: 85,
    isFeatured: true,
    stock: 300,
    images: ["https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=600"],
    brand: { name: "Pentel", slug: "pentel" },
    category: { name: "Kalemler & Yazı Gereçleri", slug: "kalemler-yazi-gerecleri" },
    reviews: [],
    description: "Pentel EnerGel Jel Kalem 5'li set ile pürüzsüz yazı deneyimi yaşayın.",
  },
  {
    id: "mock-5",
    slug: "koh-i-noor-sulu-boya-24lu",
    name: "Koh-i-Noor Sulu Boya 24'lü",
    price: 210,
    comparePrice: 259,
    isFeatured: true,
    stock: 60,
    images: ["https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=600"],
    brand: { name: "Koh-i-Noor", slug: "koh-i-noor" },
    category: { name: "Boyalar & Renkler", slug: "boyalar-renkler" },
    reviews: [],
    description: "Koh-i-Noor Sulu Boya 24'lü ile sanatsal çalışmalarınıza renk katın.",
  },
  {
    id: "mock-6",
    slug: "staedtler-spiralli-a4-defter",
    name: "Staedtler Spiralli A4 Defter 100 Yaprak",
    price: 45,
    comparePrice: null,
    isFeatured: true,
    stock: 500,
    images: ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600"],
    brand: { name: "Staedtler", slug: "staedtler" },
    category: { name: "Defterler & Ajandalar", slug: "defterler-ajandalar" },
    reviews: [],
    description: "Staedtler Spiralli A4 Defter ile notlarınızı düzenli tutun.",
  },
  {
    id: "mock-7",
    slug: "faber-castell-akrilik-boya-seti-12li",
    name: "Faber-Castell Akrilik Boya Seti 12'li",
    price: 249.9,
    comparePrice: 299.9,
    isFeatured: false,
    stock: 90,
    images: ["https://images.unsplash.com/photo-1512314889357-e157c22f938d?w=600"],
    brand: { name: "Faber-Castell", slug: "faber-castell" },
    category: { name: "Sanat Malzemeleri", slug: "sanat-malzemeleri" },
    reviews: [],
    description: "Tuval ve hobi çalışmalarına uygun zengin pigmentli akrilik boya seti.",
  },
  {
    id: "mock-8",
    slug: "mopak-a4-kapakli-odev-dosyasi-5li",
    name: "Mopak A4 Kapaklı Ödev Dosyası 5'li",
    price: 79.9,
    comparePrice: 99.9,
    isFeatured: false,
    stock: 220,
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600"],
    brand: { name: "Mopak", slug: "mopak" },
    category: { name: "Okul Gereçleri", slug: "okul-gerecleri" },
    reviews: [],
    description: "Ders notları ve ödevleri düzenli saklamak için dayanıklı kapaklı dosya seti.",
  },
];

export const reviewPool = [
  { fullName: "Ayşe Demir", comment: "Ürünün malzeme kalitesi tahminimden iyi çıktı, çok memnun kaldım." },
  { fullName: "Murat Çelik", comment: "Kargo hızlıydı ve ürün fotoğraftakinin aynısı geldi." },
  { fullName: "Zeynep Şahin", comment: "Renkler çok canlı, özellikle günlük kullanımda çok işime yaradı." },
  { fullName: "Can Yılmaz", comment: "Fiyat performans olarak beklentimin üstünde bir ürün." },
  { fullName: "Selin Aksoy", comment: "Paketleme özenliydi, üründe hiçbir deformasyon yoktu." },
  { fullName: "Emre Korkmaz", comment: "Uzun süreli kullanımda da performansı düşmedi." },
  { fullName: "Ece Arslan", comment: "Yeni başlayanlar için de profesyoneller için de gayet uygun." },
  { fullName: "Barış Kaya", comment: "Tasarımı ve kullanım rahatlığı nedeniyle tekrar sipariş vereceğim." },
];

export const fallbackCategories = [
  { id: "cat-1", name: "Kalemler & Yazı Gereçleri", slug: "kalemler-yazi-gerecleri", _count: { products: 12 } },
  { id: "cat-2", name: "Defterler & Ajandalar", slug: "defterler-ajandalar", _count: { products: 8 } },
  { id: "cat-3", name: "Sanat Malzemeleri", slug: "sanat-malzemeleri", _count: { products: 10 } },
  { id: "cat-4", name: "Okul Gereçleri", slug: "okul-gerecleri", _count: { products: 7 } },
];

export const fallbackBrands = [
  { id: "brand-1", name: "Faber-Castell", slug: "faber-castell" },
  { id: "brand-2", name: "Staedtler", slug: "staedtler" },
  { id: "brand-3", name: "Pelikan", slug: "pelikan" },
  { id: "brand-4", name: "Pentel", slug: "pentel" },
  { id: "brand-5", name: "Koh-i-Noor", slug: "koh-i-noor" },
  { id: "brand-6", name: "Mopak", slug: "mopak" },
];
