ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "premiumUntil" TIMESTAMP(3);

ALTER TABLE "Order"
  ADD COLUMN IF NOT EXISTS "premiumDiscount" DECIMAL(10,2) NOT NULL DEFAULT 0;

ALTER TABLE "Coupon"
  ADD COLUMN IF NOT EXISTS "maxOrderAmount" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "scope" TEXT NOT NULL DEFAULT 'ALL',
  ADD COLUMN IF NOT EXISTS "targetId" TEXT,
  ADD COLUMN IF NOT EXISTS "ruleType" TEXT NOT NULL DEFAULT 'DISCOUNT',
  ADD COLUMN IF NOT EXISTS "buyQuantity" INTEGER,
  ADD COLUMN IF NOT EXISTS "getQuantity" INTEGER,
  ADD COLUMN IF NOT EXISTS "freeProductId" TEXT,
  ADD COLUMN IF NOT EXISTS "freeProductQuantity" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "premiumOnly" BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS "PremiumMembership" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'AWAITING_PAYMENT',
  "amount" DECIMAL(10,2) NOT NULL,
  "startsAt" TIMESTAMP(3) NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "paymentRef" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PremiumMembership_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "PremiumMembership_userId_status_idx"
  ON "PremiumMembership"("userId", "status");
CREATE INDEX IF NOT EXISTS "PremiumMembership_expiresAt_idx"
  ON "PremiumMembership"("expiresAt");
DO $$ BEGIN
  ALTER TABLE "PremiumMembership"
    ADD CONSTRAINT "PremiumMembership_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "SiteSettings"
  ADD COLUMN IF NOT EXISTS "premiumEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "premiumPrice" DECIMAL(10,2) NOT NULL DEFAULT 79,
  ADD COLUMN IF NOT EXISTS "premiumDiscountType" TEXT NOT NULL DEFAULT 'PERCENTAGE',
  ADD COLUMN IF NOT EXISTS "premiumDiscountValue" DECIMAL(10,2) NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "premiumFreeShipping" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "premiumLogoText" TEXT NOT NULL DEFAULT 'Göçmen Premium Üyesi';